Adding fosdem 2017 event to opensourcedesign.net
opensourcedesign/events pull request #44
Opened 2016-08-27 13:44 UTC by ei8fdb

This is a duplicate of the FOSDEM 2016 event. I’ve dated this for 10
Oct 2016.

I guess once the organisers have decided to accept our room we can push it merge it….

2016-10-07 11:33 UTC, evalica commented
Hi :) I guess I should have looked at the PRs first and then create a new one. 

Anyway, there is also https://github.com/opensourcedesign/events/pull/46 

Still I don't understand why there are 3 events in this PR.

2017-01-18 10:45 UTC, jancborchardt requested changes
There’s too many events in this pull request @ei8fdb ;) and as of now, only one (the Internet Freedom Festival one) is not in the events list.

So I cherry-picked your commit with that one and put it in a pull request at https://github.com/opensourcedesign/events/pull/61 – please review :)

2017-01-18 10:45 UTC, jancborchardt commented on _posts/2016-04-15-libregraphicsmeeting.markdown
> +status: future
We already have this event. :)

2017-01-18 10:45 UTC, jancborchardt commented on _posts/2016-10-10-fosdem.markdown
> +title:  "Fosdem 2017"
We already have this through #46 as @evalica said :) can you remove the file?

2017-01-18 10:45 UTC, jancborchardt commented on _posts/2017-03-06-internetfreedomfestival.markdown
> +The [Communications and Design theme](https://internetfreedomfestival.org/#themes) will connect designers, users, and developers to keep the tools secure and usable.
Thanks for adding this! :)

2017-01-18 10:45 UTC, closed without merging